### ISSUE TITLE
Always get stop after startup complete

### ISSUE THREAD

**Issue by david50407** [docker/dockercraft#10]
I got this message and the server auto-shutdown by itself:

```
$ docker-compose up
dockercraft_1 | Log: [10:40:52] --- Started Log ---
dockercraft_1 | Log: [10:40:52] Cuberite Jenkins clang x64 Release (master) build id: #236
dockercraft_1 | Log: [10:40:52] from commit id: da20a8a09b324c07915c8468e43c4fb208c118f9 built at: Fri  6 Nov 11:27:03 CET 2015
dockercraft_1 | Log: [10:40:52] Creating new server instance...
dockercraft_1 | Log: [10:40:52] Reading server config...
dockercraft_1 | Log: [10:40:52] Starting server...
dockercraft_1 | Info: [10:40:52] Compatible clients: 1.7.x, 1.8.x
dockercraft_1 | Info: [10:40:52] Compatible protocol versions 4, 5, 47
dockercraft_1 | Warning: [10:40:52] WebServer: The server is running in unsecured HTTP mode.
dockercraft_1 | Info: [10:40:52] Put a valid HTTPS certificate in file 'webadmin/httpscert.crt' and its corresponding private key to 'webadmin/httpskey.pem' (without any password) to enable HTTPS support
dockercraft_1 | Warning: [10:40:52] Cannot open file "crafting.txt", no crafting recipes will be available!
dockercraft_1 | Log: [10:40:52] Could not open the furnace recipes file "furnace.txt". No furnace recipes are available.
dockercraft_1 | Log: [10:40:52] Could not open the brewing recipes file "brewing.txt". No brewing recipes are available.
dockercraft_1 | Log: [10:40:52] -- Loading Plugins --
dockercraft_1 | Log: [10:40:52] Initialized ChatLog v.3
dockercraft_1 | Log: [10:40:52] Initialised Core v.15
dockercraft_1 | Log: [10:40:52] Initialised Docker v.1
dockercraft_1 | Log: [10:40:52] Initialized TransAPI v.1
dockercraft_1 | Log: [10:40:52] -- Loaded 4 Plugins --
dockercraft_1 | Warning: [10:40:52] Initialize: Cannot read monsters.ini file, monster attributes not available
dockercraft_1 | Warning: [10:40:52] Cannot open file Prefabs/Villages/PlainsVillage.cubeset for reading
dockercraft_1 | Warning: [10:40:52] Cannot open file Prefabs/Villages/SandVillage.cubeset for reading
dockercraft_1 | Log: [10:40:53] Startup complete, took 996ms!
dockercraft_1 | Log: [10:40:53] Shutting down server...
dockercraft_1 | Log: [10:40:54] Unloading worlds...
dockercraft_1 | Log: [10:40:54] Disabled Core!
dockercraft_1 | Log: [10:40:54] Disabled TransAPI!
dockercraft_1 | Log: [10:40:54] Cleaning up...
dockercraft_1 | Warning: [10:40:54] Couldn't notify the input thread; the server will hang before shutdown!
dockercraft_1 | Log: [10:40:54] Shutdown successful!
dockercraft_1 | Log: [10:40:54] --- Stopped Log ---
srv_dockercraft exited with code 0
Gracefully stopping... (press Ctrl+C again to force)
```

And my docker compose yml is:
```
dockercraft:
  container_name: srv_dockercraft
  image: gaetan/dockercraft
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  ports:
    - "25565:25565"
```

**Comment by aduermael** [comment]
Apparently a tty is required. Try with this compose file:
```yml
dockercraft:
  container_name: srv_dockercraft
  image: gaetan/dockercraft
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  ports:
    - "25565:25565"
  tty: true
```
